import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import WhatsAppBtn from "@/components/WhatsAppBtn/WhatsAppBtn";
import DarkFooter from "@/components/DarkFooter";
import CallBtn from "@/components/CallBtn/CallBtn";
import { ToastContainer } from "react-toastify";


export const metadata = {
  title: "Solvent",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="hydrated">
      <body suppressHydrationWarning>
        <Navbar />
        {children}
        <ToastContainer position="top-right" theme="dark" toastStyle={{ backgroundColor: "#0f172a", color: "#fff" }}/>
        <CallBtn />
        <WhatsAppBtn />
        <Footer />
        <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
        <script noModule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
      </body>
    </html>
  );
}
